#!/bin/bash
set -e

image="${REGISTRY}/${IMAGE_NAME}"
flavor="${1:-${GITHUB_RUN_NUMBER:-unknown}}"

version="$(git describe --tags --abbrev=0)"

# Get the current git branch and hash
git_info=""
ref_name="$(git rev-parse --abbrev-ref HEAD)"
if [ "$ref_name" != "HEAD" ]; then
    git_info="$ref_name @ "
fi

git_info+="$(git rev-parse --short HEAD)"

# Grab the major and major.minor versions and use the as tags
major_minor="$(echo "${version}" | grep -Po '^v\d+\.\d+' || :)"
major="$(echo "${version}" | grep -Po '^v[1-9][0-9]*' || :)"

if [ -n "${major_minor}" ]; then
    addtional_tags="${image}:${major_minor}"
fi

if [ -n "${major}" ]; then
    if [ -n "${addtional_tags}" ]; then
        addtional_tags+=","
    fi

    addtional_tags+="${image}:${major}"
fi

# Get the java engine hash
engine_hash="$(cd engine; git rev-parse --short HEAD)"
engine_version="$(grep -Po '<version>\K[^<]+' engine/pom.xml  | head -1)"

build_info="UI ${version}-${flavor} ${git_info} - Engine ${engine_version} @ ${engine_hash}"

if [ -n "$GITHUB_OUTPUT" ]; then
    echo "version=$version" >> "$GITHUB_OUTPUT"
    echo "build_info=$build_info" >> "$GITHUB_OUTPUT"
    echo "additional_tags=$addtional_tags" >> "$GITHUB_OUTPUT"
fi

echo "$build_info"