#!/bin/bash

if [ "$1" != "trigger-hook" ]; then
    echo -n "Installing git hook..."
    hook="$(git rev-parse --git-dir)/hooks/pre-commit"
    echo -e '#!/bin/bash\nexec "$(git rev-parse --show-toplevel)/scripts/git-hook" trigger-hook' >"$hook"
    chmod +x "$hook"
    echo "done"
    exit
fi

verify_log="$(mktemp)"
trap "rm $verify_log" EXIT

run() {
    echo -n "Running $1..."
    shift

    "$@" &>$verify_log
    if [ $? -ne 0 ]; then
        echo -e "\e[1;31mfail\e[0m"
        cat "$verify_log"
        echo -e "\nTo commit anyway run git commit --no-verify"
        exit 1
    fi

    echo -e "\e[1;32mpass\e[0m"
}


run "unit tests" npm run test
